# Build stuff
os: linux
dist: trusty
language: node_js
node_js:
  - 11

# Config stuff
git:
  quiet: true

notifications:
  webhooks: $DISCORD_WEBHOOK
    on_success: change
    on_failure: always
    on_start:   change
    on_cancel:  always
    on_error:   always

# Run tests
fast_finish: true

script:
  - npm test
