os: linux
dist: trusty

language: node_js
node_js:
  - "10"

cache:
  directories:
     - ./node_modules

install:
  - cd dock
  - npm install
  - cd ..
  - cd skidbladnir
  - npm install
  - cd ..

jobs:
  include:
    - script:
        - cd dock
        - npm test
        - cd ..
        - cd skidbladnir
        - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
        - cd ..
